
print ("Bienvenido a la librería Maxi Dog")
print ("-"*80+  "\n")
print ("¿Qué es lo que deseas hacer el día de hoy? Introduce el nombre de la función y después aprieta enter")

print("Suma")
print("Resta")
print("Multiplicación")
print("División")
print("Potencia")
print("Raíz")
print("Módulo")
print("Conversión de binario a hexadecimal")
print("Conversión de hexadecimal a binario")
print("Conversión de decimal a hexadecimal")
print("Conversión de hexadecimal a decimal")
print("Conversión de binario a decimal")
print("Conversión de decimal a binario")
print("Metros a Yardas")
print("Metros a pulgadas")
print ("-"*80+  "\n")


operacion=input()
operacion=str.lower(operacion)
